import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`antialiased flex flex-col h-dvh justify-center items-center bg-linear-to-r from-[#ff75c3] via-[#ffa647] to-[#ffea3f]`}
      >
        {children}
      </body>
    </html>
  );
}
